[package]
name = "simpzip"
version = "0.1.0"
authors = ["Dmitry Sazonov <rainyday170120@gmail.com>"]
edition = "2018"

[dependencies]
dir-diff = "0.3.2"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3